title: "Keep it simple, stupid"
user: "Xiao-Ou Zhang"

author:
    name: "Xiao-Ou Zhang, PhD"
    description: "I'm a computational biologist who is passionate about <a href='https://scholar.google.com/citations?user=KpX6MewAAAAJ'>RNA</a>, <a href='https://github.com/kepbod'>data mining</a> and computational reproducibility."
    twitter: "https://twitter.com/kepbod"
    linkedin: "http://cn.linkedin.com/in/kepbod"
    github: "https://github.com/kepbod"
    email: "xozhang1989@gmail.com"
