title: Xiao-Ou Zhang's Lab
user: Xiao-Ou Zhang
author:
  name: Xiao-Ou Zhang, PhD
  description: Principal Investigator and Group Leader, Tongji University. <br/>I'm a <a href='xiaoou_zhang_cv.pdf'>computational biologist</a> who
    is passionate about <a href='https://scholar.google.com/citations?user=KpX6MewAAAAJ'>noncoding sequence and data mining</a>!
gems: [github-pages]
